### ISSUE TITLE
Lay out de eventos sugestão

### ISSUE THREAD

**Issue by donsalvatore** [hacklabr/cultural#40]
Olá, sei que não é prioridade mas vendo o site como um todo (que está bonitão), ao entrar em eventos (alimentado pelo SPcultura) parece que entramos em outro site por conta do layout. Não sei como fazer a crítica ou o apontamento, mas aqueles quadrados de serviço com espaços enormes de vazio deixam a coisa, digamos feia.

segue exemplo do uso pela serralheria
http://escapeserralheria.com/eventos/

algo nesse estilo, como ref, ficaria melhor e aproveitaria melhor o espaço.
enfim... é apenas um obs ok? http://www.circuitospdecultura.prefeitura.sp.gov.br/agenda/

**Comment by rafaelchavesfreitas** [comment]
o layout foi aprovado....
