### ISSUE TITLE
Categorias estão puxando um post ao invés do que se programa para fazer (eventos)

### ISSUE THREAD

**Issue by donsalvatore** [hacklabr/cultural#44]

**Comment by rafaelchavesfreitas** [comment]
Talvez só documentar que é necessário ao menos um post na categoria.

**Comment by donsalvatore** [comment]
isso mesmo.

**Comment by rafaelchavesfreitas** [comment]
resolvi da seguinte forma:
quando uma categoria não tem posts mas tem uma  agenda associada, redireciona para a agenda, senão mostra uma mensagem de "nenhum post encontrado"
