### ISSUE TITLE
Criar novos metodos na API do Mapas culturais

### ISSUE THREAD

**Issue by leandrodb** [hacklabr/cultural#5]

**Comment by leandrodb** [comment]
- [x] Listas de termos de taxonomias;
- [x] Lista de Geo Divisions;
- [x] api/event/findBySpace aceitar lista de ids de espaços

**Comment by donsalvatore** [comment]
Bó!!!
só uma questão.
Existem 2 sites pendurados no spcultura usando as APIs.
estas mudanças, desculpe a ignorância, alteram o funcionamento dos sites
que usam o SPCULTURA?

Em 3 de fevereiro de 2015 20:43, Leandro Monteiro dal Bò <
notifications@github.com> escreveu:

> -  Listas de termos de taxonomias;
> -  Lista de Geo Divisions;
> -  api/event/findBySpace aceitar lista de ids de espaços
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hacklabr/cultural/issues/5#issuecomment-72752068.

## 

Miguel de Castro Perez
http://about.me/migueldecastro
@serra_lheria
cel.: +55 11 97161 2502

**Comment by leandrodb** [comment]
Não, @donsalvatore! Vamos manter a API compatível com os sistemas que atualmente a utilizam. Vamos acrescentar coisas novas. Se precisarmos modificar algo que já existe, vamos manter a forma atual e fazer uma nova em paralelo, como no caso dos dois ou mais projetos por evento, que modifica bastante coisas, mas vamos manter funcionando a forma atual. Quando a API evoluir muito podemos criar uma versão 2 dela e manter a versão 1 no ar para esses sistemas antigos. Enfim, são coisas sempre a serel levadas em conta e pode ter certeza que estamos levando e agradecemos a lembrança!

**Comment by donsalvatore** [comment]
;)

valeu brou

Em 3 de fevereiro de 2015 21:02, Leandro Monteiro dal Bò <
notifications@github.com> escreveu:

> Não, @donsalvatore https://github.com/donsalvatore! Vamos manter a API
> compatível com os sistemas que atualmente a utilizam. Vamos acrescentar
> coisas novas. Se precisarmos modificar algo que já existe, vamos manter a
> forma atual e fazer uma nova em paralelo, como no caso dos dois ou mais
> projetos por evento, que modifica bastante coisas, mas vamos manter
> funcionando a forma atual. Quando a API evoluir muito podemos criar uma
> versão 2 dela e manter a versão 1 no ar para esses sistemas antigos. Enfim,
> são coisas sempre a serel levadas em conta e pode ter certeza que estamos
> levando e agradecemos a lembrança!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hacklabr/cultural/issues/5#issuecomment-72755187.

## 

Miguel de Castro Perez
http://about.me/migueldecastro
@serra_lheria
cel.: +55 11 97161 2502
