### ISSUE TITLE
"VER EVENTOS" quando dentro de uma categoria

### ISSUE THREAD

**Issue by donsalvatore** [hacklabr/cultural#51]
conforme print anexa, deixar mais evidente ou mais clara essa possibilidade de ver mais eventos
(link no canto superior esquerdo)

**Comment by donsalvatore** [comment]
![untitled](https://cloud.githubusercontent.com/assets/2921891/7353485/43f7bb6e-ecea-11e4-929f-78ef0ead8d3e.jpg)

**Comment by rafaelchavesfreitas** [comment]
mesma que #31
